// ── Timetable Config Types ──

export interface TimetableSlot {
  slotNumber: number;
  type: 'period' | 'break';
  label: string;
  startTime: string; // HH:mm
  endTime: string;
}

export interface DaySchedule {
  dayOfWeek: number; // 0=Sunday…6=Saturday
  slots: TimetableSlot[];
}

export interface TimetableConfig {
  _id: string;
  name: string;
  academicYearId: string | { _id: string; name: string; startDate: string; endDate: string };
  workingDays: number[];
  daySchedules: DaySchedule[];
  status: 'active' | 'inactive';
  organizationId: string;
  branchId: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateTimetableConfigData {
  name: string;
  academicYearId: string;
  workingDays: number[];
  daySchedules: DaySchedule[];
  status?: 'active' | 'inactive';
  branchId?: string;
}

// ── Timetable Types ──

export interface TimetableEntry {
  dayOfWeek: number;
  slotNumber: number;
  subjectId: string;
  subjectName: string;
  staffId: string;
  staffName: string;
}

export interface Timetable {
  _id: string;
  classId: string | { _id: string; name: string };
  divisionId: string | { _id: string; name: string; className?: string };
  academicYearId: string | { _id: string; name: string };
  configId: string | TimetableConfig;
  entries: TimetableEntry[];
  effectiveFrom?: string;
  status: 'draft' | 'active' | 'archived';
  clonedFrom?: string;
  organizationId: string;
  branchId: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateTimetableData {
  classId: string;
  divisionId: string;
  academicYearId: string;
  configId: string;
  entries?: TimetableEntry[];
  effectiveFrom?: string;
  status?: 'draft' | 'active';
  branchId?: string;
}

export interface CloneTimetableData {
  targetClassId: string;
  targetDivisionId: string;
}

export interface CheckConflictsData {
  configId: string;
  academicYearId: string;
  entries: TimetableEntry[];
  excludeTimetableId?: string;
}

export interface TeacherConflict {
  staffId: string;
  staffName: string;
  dayOfWeek: number;
  slotNumber: number;
  time: string;
  conflictWith: {
    timetableId: string;
    className: string;
    divisionName: string;
  };
}

export interface TeacherScheduleEntry extends TimetableEntry {
  timetableId: string;
  className: string;
  divisionName: string;
  academicYear: string;
  config: TimetableConfig;
}

export interface TeacherScheduleResponse {
  staffId: string;
  staffName: string;
  timetables: Timetable[];
  schedule: TeacherScheduleEntry[];
}

export interface TimetableConfigQueryParams {
  page?: number;
  limit?: number;
  search?: string;
  academicYearId?: string;
  status?: string;
}

export interface TimetableQueryParams {
  page?: number;
  limit?: number;
  classId?: string;
  divisionId?: string;
  academicYearId?: string;
  status?: string;
}

export const DAY_NAMES = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'] as const;
export const DAY_SHORT = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] as const;

// ── Auto-generate Types ──

export interface SubjectTeacherMapping {
  subjectId: string;
  subjectName: string;
  staffId: string;
  staffName: string;
  periodsPerWeek: number;
}

export interface AutoGenerateData {
  classId: string;
  divisionId: string;
  academicYearId: string;
  configId: string;
  subjectTeacherMappings: SubjectTeacherMapping[];
  useAI?: boolean;
}

export interface AutoGenerateResult {
  timetable: Timetable;
  method: 'algorithm' | 'ai';
  stats: {
    totalPlaced: number;
    unplaced: Array<{ subjectName: string; staffName: string; remaining: number }>;
  };
  aiAvailable: boolean;
}
