import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { timetableConfigService, timetableService } from '@/services/timetableService';
import { useToast } from '@/hooks/use-toast';
import type {
  TimetableConfigQueryParams,
  TimetableQueryParams,
  CreateTimetableConfigData,
  CreateTimetableData,
  CloneTimetableData,
  CheckConflictsData,
  TimetableEntry,
  TeacherScheduleResponse,
  AutoGenerateData,
} from '@/types/timetable';

// ── Query Keys ──

export const timetableConfigKeys = {
  all: ['timetable-configs'] as const,
  lists: () => [...timetableConfigKeys.all, 'list'] as const,
  list: (params: TimetableConfigQueryParams) => [...timetableConfigKeys.lists(), params] as const,
  details: () => [...timetableConfigKeys.all, 'detail'] as const,
  detail: (id: string) => [...timetableConfigKeys.details(), id] as const,
};

export const timetableKeys = {
  all: ['timetables'] as const,
  lists: () => [...timetableKeys.all, 'list'] as const,
  list: (params: TimetableQueryParams) => [...timetableKeys.lists(), params] as const,
  details: () => [...timetableKeys.all, 'detail'] as const,
  detail: (id: string) => [...timetableKeys.details(), id] as const,
  byClass: (classId: string, divisionId: string) => [...timetableKeys.all, 'by-class', classId, divisionId] as const,
  myTimetable: () => [...timetableKeys.all, 'my-timetable'] as const,
  mySchedule: () => [...timetableKeys.all, 'my-schedule'] as const,
  staffSchedule: (staffId: string) => [...timetableKeys.all, 'staff', staffId] as const,
};

// ── Timetable Config Hooks ──

export const useTimetableConfigs = (params?: TimetableConfigQueryParams) => {
  return useQuery({
    queryKey: timetableConfigKeys.list(params || {}),
    queryFn: () => timetableConfigService.getConfigs(params),
    staleTime: 5 * 60 * 1000,
  });
};

export const useTimetableConfig = (id: string) => {
  return useQuery({
    queryKey: timetableConfigKeys.detail(id),
    queryFn: () => timetableConfigService.getConfig(id),
    enabled: !!id,
  });
};

export const useCreateTimetableConfig = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: (data: CreateTimetableConfigData) => timetableConfigService.createConfig(data),
    onSuccess: (response) => {
      queryClient.invalidateQueries({ queryKey: timetableConfigKeys.all });
      toast({ title: 'Success', description: response.message || 'Config created successfully' });
    },
    onError: (error: any) => {
      toast({
        title: 'Error',
        description: error.response?.data?.message || 'Something went wrong while creating the timetable config. Please try again.',
        variant: 'destructive',
      });
    },
  });
};

export const useUpdateTimetableConfig = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: Partial<CreateTimetableConfigData> }) =>
      timetableConfigService.updateConfig(id, data),
    onSuccess: (response) => {
      queryClient.invalidateQueries({ queryKey: timetableConfigKeys.all });
      toast({ title: 'Success', description: response.message || 'Config updated successfully' });
    },
    onError: (error: any) => {
      toast({
        title: 'Error',
        description: error.response?.data?.message || 'Something went wrong while updating the timetable config. Please try again.',
        variant: 'destructive',
      });
    },
  });
};

export const useDeleteTimetableConfig = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: (id: string) => timetableConfigService.deleteConfig(id),
    onSuccess: (response) => {
      queryClient.invalidateQueries({ queryKey: timetableConfigKeys.all });
      toast({ title: 'Success', description: response.message || 'Config deleted successfully' });
    },
    onError: (error: any) => {
      toast({
        title: 'Error',
        description: error.response?.data?.message || 'Something went wrong while deleting the timetable config. Please try again.',
        variant: 'destructive',
      });
    },
  });
};

// ── Timetable Hooks ──

export const useTimetables = (params?: TimetableQueryParams) => {
  return useQuery({
    queryKey: timetableKeys.list(params || {}),
    queryFn: () => timetableService.getTimetables(params),
    staleTime: 5 * 60 * 1000,
  });
};

export const useTimetable = (id: string) => {
  return useQuery({
    queryKey: timetableKeys.detail(id),
    queryFn: () => timetableService.getTimetable(id),
    enabled: !!id,
  });
};

export const useTimetableByClass = (classId: string, divisionId: string) => {
  return useQuery({
    queryKey: timetableKeys.byClass(classId, divisionId),
    queryFn: () => timetableService.getByClass(classId, divisionId),
    enabled: !!classId && !!divisionId,
    retry: false,
  });
};

export const useMyTimetable = () => {
  return useQuery({
    queryKey: timetableKeys.myTimetable(),
    queryFn: () => timetableService.getMyTimetable(),
    staleTime: 10 * 60 * 1000,
  });
};

export const useMySchedule = () => {
  return useQuery({
    queryKey: timetableKeys.mySchedule(),
    queryFn: () => timetableService.getMySchedule(),
    staleTime: 5 * 60 * 1000,
  });
};

export const useStaffTimetable = (staffId: string) => {
  return useQuery({
    queryKey: timetableKeys.staffSchedule(staffId),
    queryFn: () => timetableService.getStaffSchedule(staffId),
    enabled: !!staffId,
  });
};

export const useCreateTimetable = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: (data: CreateTimetableData) => timetableService.createTimetable(data),
    onSuccess: (response) => {
      queryClient.invalidateQueries({ queryKey: timetableKeys.all });
      toast({ title: 'Success', description: response.message || 'Timetable created successfully' });
    },
    onError: (error: any) => {
      toast({
        title: 'Error',
        description: error.response?.data?.message || 'Something went wrong while creating the timetable. Please try again.',
        variant: 'destructive',
      });
    },
  });
};

export const useUpdateTimetable = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: { entries?: TimetableEntry[]; effectiveFrom?: string | null } }) =>
      timetableService.updateTimetable(id, data),
    onSuccess: (response) => {
      queryClient.invalidateQueries({ queryKey: timetableKeys.all });
      toast({ title: 'Success', description: response.message || 'Timetable updated successfully' });
    },
    onError: (error: any) => {
      toast({
        title: 'Error',
        description: error.response?.data?.message || 'Something went wrong while updating the timetable. Please try again.',
        variant: 'destructive',
      });
    },
  });
};

export const useActivateTimetable = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: (id: string) => timetableService.activateTimetable(id),
    onSuccess: (response) => {
      queryClient.invalidateQueries({ queryKey: timetableKeys.all });
      toast({ title: 'Success', description: response.message || 'Timetable activated successfully' });
    },
    onError: (error: any) => {
      toast({
        title: 'Error',
        description: error.response?.data?.message || 'Something went wrong while activating the timetable. Please try again.',
        variant: 'destructive',
      });
    },
  });
};

export const useCloneTimetable = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: CloneTimetableData }) =>
      timetableService.cloneTimetable(id, data),
    onSuccess: (response) => {
      queryClient.invalidateQueries({ queryKey: timetableKeys.all });
      toast({ title: 'Success', description: response.message || 'Timetable cloned successfully' });
    },
    onError: (error: any) => {
      toast({
        title: 'Error',
        description: error.response?.data?.message || 'Something went wrong while cloning the timetable. Please try again.',
        variant: 'destructive',
      });
    },
  });
};

export const useDeleteTimetable = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: (id: string) => timetableService.deleteTimetable(id),
    onSuccess: (response) => {
      queryClient.invalidateQueries({ queryKey: timetableKeys.all });
      toast({ title: 'Success', description: response.message || 'Timetable deleted successfully' });
    },
    onError: (error: any) => {
      toast({
        title: 'Error',
        description: error.response?.data?.message || 'Something went wrong while deleting the timetable. Please try again.',
        variant: 'destructive',
      });
    },
  });
};

export const useCheckConflicts = () => {
  const { toast } = useToast();

  return useMutation({
    mutationFn: (data: CheckConflictsData) => timetableService.checkConflicts(data),
    onError: (error: any) => {
      toast({
        title: 'Error',
        description: error.response?.data?.message || 'Something went wrong while checking for conflicts. Please try again.',
        variant: 'destructive',
      });
    },
  });
};

export const useAutoGenerate = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();

  return useMutation({
    mutationFn: (data: AutoGenerateData) => timetableService.autoGenerate(data),
    onSuccess: (response) => {
      queryClient.invalidateQueries({ queryKey: timetableKeys.all });
      toast({ title: 'Success', description: response.message || 'Timetable auto-generated' });
    },
    onError: (error: any) => {
      toast({
        title: 'Error',
        description: error.response?.data?.message || 'Something went wrong while auto-generating the timetable. Please try again.',
        variant: 'destructive',
      });
    },
  });
};
