import { apiClient } from '@/lib/api';
import type {
  TimetableConfig,
  CreateTimetableConfigData,
  TimetableConfigQueryParams,
  Timetable,
  CreateTimetableData,
  TimetableQueryParams,
  CloneTimetableData,
  CheckConflictsData,
  TeacherConflict,
  TimetableEntry,
  TeacherScheduleResponse,
  AutoGenerateData,
  AutoGenerateResult,
} from '@/types/timetable';

// ── Timetable Config Service ──

export const timetableConfigService = {
  getConfigs: async (params?: TimetableConfigQueryParams) => {
    const res = await apiClient.get<TimetableConfig[]>('/timetable-configs', params);
    return res.data;
  },

  getConfig: async (id: string) => {
    const res = await apiClient.get<TimetableConfig>(`/timetable-configs/${id}`);
    return res.data;
  },

  createConfig: async (data: CreateTimetableConfigData) => {
    const res = await apiClient.post<TimetableConfig>('/timetable-configs', data);
    return res.data;
  },

  updateConfig: async (id: string, data: Partial<CreateTimetableConfigData>) => {
    const res = await apiClient.put<TimetableConfig>(`/timetable-configs/${id}`, data);
    return res.data;
  },

  deleteConfig: async (id: string) => {
    const res = await apiClient.delete(`/timetable-configs/${id}`);
    return res.data;
  },
};

// ── Timetable Service ──

export const timetableService = {
  getTimetables: async (params?: TimetableQueryParams) => {
    const res = await apiClient.get<Timetable[]>('/timetables', params);
    return res.data;
  },

  getTimetable: async (id: string) => {
    const res = await apiClient.get<Timetable>(`/timetables/${id}`);
    return res.data;
  },

  getByClass: async (classId: string, divisionId: string) => {
    const res = await apiClient.get<Timetable>(`/timetables/by-class/${classId}/${divisionId}`);
    return res.data;
  },

  getMyTimetable: async () => {
    const res = await apiClient.get<Timetable>('/timetables/my-timetable');
    return res.data;
  },

  getMySchedule: async () => {
    const res = await apiClient.get<TeacherScheduleResponse>('/timetables/my-schedule');
    return res.data;
  },

  getStaffSchedule: async (staffId: string) => {
    const res = await apiClient.get<any[]>(`/timetables/staff/${staffId}`);
    return res.data;
  },

  createTimetable: async (data: CreateTimetableData) => {
    const res = await apiClient.post<Timetable>('/timetables', data);
    return res.data;
  },

  updateTimetable: async (id: string, data: { entries?: TimetableEntry[]; effectiveFrom?: string | null }) => {
    const res = await apiClient.put<Timetable>(`/timetables/${id}`, data);
    return res.data;
  },

  activateTimetable: async (id: string) => {
    const res = await apiClient.put<Timetable>(`/timetables/${id}/activate`);
    return res.data;
  },

  cloneTimetable: async (id: string, data: CloneTimetableData) => {
    const res = await apiClient.post<Timetable>(`/timetables/${id}/clone`, data);
    return res.data;
  },

  deleteTimetable: async (id: string) => {
    const res = await apiClient.delete(`/timetables/${id}`);
    return res.data;
  },

  checkConflicts: async (data: CheckConflictsData) => {
    const res = await apiClient.post<{ hasConflicts: boolean; conflicts: TeacherConflict[] }>(
      '/timetables/check-conflicts',
      data
    );
    return res.data;
  },

  autoGenerate: async (data: AutoGenerateData) => {
    const res = await apiClient.post<AutoGenerateResult>('/timetables/auto-generate', data);
    return res.data;
  },
};
